name: CalledWorkflow

on:
  repository_dispatch:
    types: [CalledWorkflow]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      parameter1: ${{ github.event.client_payload.prameter1 }} #this parameter will reached by caller workflow
      parameter2: ${{ github.event.client_payload.parameter2 }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo hello ashraf test passed

      - name: Run a multi-line script
        run: |
          echo add other actions to build,
          echo test, and deploy your project
          echo $parameter1 
          #this parameters will be featching from the called workflow
          echo $parameter2
          
    
    
